from textwrap import dedent

code = dedent('''
# -*- coding: utf-8 -*-
"""GA4 자동화 이메일 11.24 ver

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvA7oBOH4oOzw3DlqT9fyUhwZ1iwoNbc
"""


#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Columbia Sportswear Korea
Daily eCommerce Performance Digest (GA4 + HTML Mail)

- GA4 기준 KPI, 퍼널, 채널, 상품, 페이지, 온사이트 검색 요약을
  데일리 HTML 다이제스트로 생성해서 메일 발송하는 스크립트.
- 상단: 타이틀 + 설명
- 그 아래: 오늘의 인사이트 / 오늘 취할 액션 2개 카드
- 01 섹션: KPI 9개 카드
- 02 섹션: 퍼널/채널/상품/검색 카드 (2 x 4 그리드)
- 시간대별 트래픽 & 매출: 섹션 2 아래 풀폭 카드로 트래픽(막대) + 매출(막대) 시각화.
"""

import os
import smtplib
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from datetime import datetime, timedelta

from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import DateRange, Dimension, Metric, RunReportRequest
from google.oauth2 import service_account


# =====================================================================
# 0) 환경 변수 / 기본 설정
# =====================================================================

# GA4
GA4_PROPERTY_ID = os.getenv("GA4_PROPERTY_ID", "358593394").strip()
# 기본값은 비워두고, 아래 candidates 리스트에서 자동 탐색
GA_ITEM_VIEW_METRIC = os.getenv("GA_ITEM_VIEW_METRIC", "").strip()

# CRM RAW 파일 경로 (현재 HTML에는 사용 안 하지만 남겨둠)
_YESTERDAY_LABEL = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
CRM_RAW_PATH = os.getenv("CRM_RAW_PATH", f"/content/orders-{_YESTERDAY_LABEL}.xls").strip()

# 메일 발송 설정
SMTP_PROVIDER = os.getenv("SMTP_PROVIDER", "gmail").lower()  # "gmail" or "outlook"
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "koreacolumbia@gmail.com")
SMTP_PASS = os.getenv("SMTP_PASS", "xxopfytdkxcyhisa")

DAILY_RECIPIENTS = [
    e.strip()
    for e in os.getenv(
        "DAILY_RECIPIENTS",
        "hugh.kang@Columbia.com").split(",")
    if e.strip()
]

ALERT_RECIPIENT = os.getenv("ALERT_RECIPIENT", "").strip()

# 임계값 (알림 트리거)
CVR_DROP_PPTS = float(os.getenv("CVR_DROP_PPTS", "0.5"))
REVENUE_DROP_PCT = float(os.getenv("REVENUE_DROP_PCT", "15"))
UV_DROP_PCT = float(os.getenv("UV_DROP_PCT", "20"))

# 퍼널 벤치마크 (이탈률 기준)
PDP_ADD2CART_MIN_PCT = float(os.getenv("PDP_ADD2CART_MIN_PCT", "6"))
CART2CHK_MIN_PCT = float(os.getenv("CART2CHK_MIN_PCT", "45"))
CHK2BUY_MIN_PCT = float(os.getenv("CHK2BUY_MIN_PCT", "60"))

SEARCH_CVR_MIN = float(os.getenv("SEARCH_CVR_MIN", "1.0"))

PRODUCT_COLS = ["상품명", "상품조회수", "구매수", "매출(만원)", "CVR(%)"]

# JPEG 인라인 이미지를 사용할지 여부 (1이면 사용)
ENABLE_INLINE_JPEG = os.getenv("DIGEST_INLINE_JPEG", "0") == "1"
HTML_SCREENSHOT_WIDTH = int(os.getenv("DIGEST_IMG_WIDTH", "1200"))


# =====================================================================
# 1) 유틸 함수
# =====================================================================

def pct_change(curr, prev):
    """(curr - prev)/prev * 100 (%). prev가 0이면 0."""
    try:
        prev = float(prev)
        curr = float(curr)
        if prev == 0:
            return 0.0
        return round((curr - prev) / prev * 100, 1)
    except Exception:
        return 0.0


def safe_int(x):
    try:
        return int(float(x))
    except Exception:
        return 0


def safe_float(x):
    try:
        return float(x)
    except Exception:
        return 0.0


def format_money(won):
    w = round(safe_float(won))
    return f"{w:,}원"


def format_money_manwon(won):
    man = round(safe_float(won) / 10_000)
    return f"{man:,}만원"


def format_date_label(ga_date_str):
    """GA4 date(YYYYMMDD or 20251121.0) → 'YYYY-MM-DD'"""
    try:
        s = str(ga_date_str)
        if "." in s:
            s = str(int(float(s)))
        d = datetime.strptime(s, "%Y%m%d")
        return d.strftime("%Y-%m-%d")
    except Exception:
        return str(ga_date_str)


# =====================================================================
# 2) 메일 유틸
# =====================================================================

def _smtp_server_and_port():
    if SMTP_PROVIDER == "gmail":
        return ("smtp.gmail.com", 587)
    elif SMTP_PROVIDER == "outlook":
        return ("smtp.office365.com", 587)
    else:
        return (SMTP_HOST, SMTP_PORT)


def html_to_jpeg(html_body: str, out_path: str = "/tmp/columbia_daily_digest.jpg") -> str:
    """HTML 문자열을 JPEG 이미지로 변환 (pyppeteer + Chromium)."""
    if not ENABLE_INLINE_JPEG:
        return ""
    try:
        from pyppeteer import launch
        import asyncio
    except Exception:
        print("[WARN] pyppeteer 미설치 – HTML 그대로 발송.")
        return ""

    async def _capture():
        browser = await launch(headless=True, args=["--no-sandbox"])
        page = await browser.newPage()
        await page.setViewport({"width": HTML_SCREENSHOT_WIDTH, "height": 1600})
        await page.setContent(html_body, waitUntil="networkidle0")
        await page.screenshot(path=out_path, fullPage=True, type="jpeg", quality=95)
        await browser.close()

    try:
        try:
            loop = asyncio.get_event_loop()
        except RuntimeError:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
        loop.run_until_complete(_capture())
        print(f"[INFO] HTML→JPEG 변환 완료: {out_path}")
        return out_path
    except Exception as e:
        print("[WARN] HTML→JPEG 변환 실패:", e)
        return ""


def send_email_html(subject: str, html_body: str, recipients, jpeg_path: str = ""):
    """HTML 또는 JPEG 버전을 메일로 발송."""
    if isinstance(recipients, str):
        recipients = [recipients]
    if not recipients:
        print("[WARN] 수신자가 없어 메일 발송 생략.")
        return

    if not (SMTP_USER and SMTP_PASS):
        print("[WARN] SMTP_USER/SMTP_PASS 없음 – 아래는 HTML 미리보기입니다.\\n")
        print(html_body[:3000])
        return

    host, port = _smtp_server_and_port()

    msg = MIMEMultipart("related")
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = ", ".join(recipients)

    alt = MIMEMultipart("alternative")
    msg.attach(alt)

    plain_text = "Columbia eCommerce Daily Digest 입니다. 메일이 제대로 보이지 않으면 이미지를 확인해주세요."
    alt.attach(MIMEText(plain_text, "plain", "utf-8"))

    if jpeg_path and os.path.exists(jpeg_path):
        html_body_effective = f"""<html><body style='margin:0; padding:0; background:#f4f6fb;'>
<div style='width:100%; text-align:center; padding:16px 0;'>
  <img src="cid:digest_image" alt="Columbia Daily eCommerce Digest" style="max-width:100%; height:auto; border:0; display:block; margin:0 auto;" />
</div>
</body></html>"""
    else:
        html_body_effective = html_body

    alt.attach(MIMEText(html_body_effective, "html", "utf-8"))

    if jpeg_path and os.path.exists(jpeg_path):
        with open(jpeg_path, "rb") as f:
            img = MIMEImage(f.read(), _subtype="jpeg")
        img.add_header("Content-ID", "<digest_image>")
        img.add_header("Content-Disposition", "inline", filename=os.path.basename(jpeg_path))
        msg.attach(img)

    with smtplib.SMTP(host, port) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.sendmail(SMTP_USER, recipients, msg.as_string())


def send_critical_alert(subject: str, body_text: str):
    recipient = ALERT_RECIPIENT or SMTP_USER or ""
    if not recipient:
        print("[WARN] ALERT_RECIPIENT/SMTP_USER 없음 – 긴급 알림 생략:", subject)
        return
    html = f"<pre style='font-family:monospace; white-space:pre-wrap'>{body_text}</pre>"
    send_email_html(subject, html, [recipient])


# =====================================================================
# 3) GA4 Client & 공통 run_report
# =====================================================================

# GitHub Actions 등에서는 GA4 서비스 계정 JSON을 환경 변수로 받아 파일로 저장해서 사용
SERVICE_ACCOUNT_JSON = os.getenv("GA4_SERVICE_ACCOUNT_JSON", "")

if SERVICE_ACCOUNT_JSON:
    SERVICE_ACCOUNT_FILE = "/tmp/ga4_service_account.json"
    with open(SERVICE_ACCOUNT_FILE, "w", encoding="utf-8") as f:
        f.write(SERVICE_ACCOUNT_JSON)
else:
    # 로컬/Colab에서 쓸 기본값 (기존 경로 그대로 유지)
    SERVICE_ACCOUNT_FILE = os.getenv(
        "GA4_SERVICE_ACCOUNT_FILE",
        "//content/drive/MyDrive/Colab Notebooks/awesome-aspect-467505-r6-02b6747c0a3b.json",
    )

def ga_client():
    if not GA4_PROPERTY_ID:
        raise SystemExit("GA4_PROPERTY_ID가 비어 있습니다.")
    if not os.path.exists(SERVICE_ACCOUNT_FILE):
        raise SystemExit(f"서비스 계정 파일을 찾을 수 없습니다: {SERVICE_ACCOUNT_FILE}")
    creds = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE,
        scopes=["https://www.googleapis.com/auth/analytics.readonly"],
    )
    return BetaAnalyticsDataClient(credentials=creds)


def ga_run_report(dimensions, metrics, start_date, end_date, limit=None, order_bys=None):
    client = ga_client()
    req = RunReportRequest(
        property=f"properties/{GA4_PROPERTY_ID}",
        date_ranges=[DateRange(start_date=start_date, end_date=end_date)],
        dimensions=[Dimension(name=d) for d in dimensions],
        metrics=[Metric(name=m) for m in metrics],
        limit=limit if limit else 0,
        order_bys=order_bys or [],
    )
    resp = client.run_report(req)
    headers = [h.name for h in resp.dimension_headers] + [h.name for h in resp.metric_headers]
    rows = []
    for r in resp.rows:
        rows.append(
            [*[d.value for d in r.dimension_values], *[m.value for m in r.metric_values]]
        )
    df = pd.DataFrame(rows, columns=headers)
    for c in df.columns:
        try:
            df[c] = pd.to_numeric(df[c])
        except Exception:
            pass
    return df


# =====================================================================
# 4) 데이터 소스 (GA4)
# =====================================================================

def src_kpi_one_day(start_date_str: str, end_date_str: str):
    df = ga_run_report(
        dimensions=["date"],
        metrics=["sessions", "transactions", "purchaseRevenue", "newUsers"],
        start_date=start_date_str,
        end_date=end_date_str,
    )
    if df.empty:
        return {
            "date": None,
            "sessions": 0,
            "transactions": 0,
            "purchaseRevenue": 0.0,
            "newUsers": 0,
        }
    row = df.iloc[0]
    return {
        "date": row["date"],
        "sessions": safe_int(row["sessions"]),
        "transactions": safe_int(row["transactions"]),
        "purchaseRevenue": safe_float(row["purchaseRevenue"]),
        "newUsers": safe_int(row["newUsers"]),
    }


def src_funnel_yesterday():
    df = ga_run_report(
        dimensions=["eventName"],
        metrics=["eventCount"],
        start_date="yesterday",
        end_date="yesterday",
    )
    want = ["view_item", "add_to_cart", "begin_checkout", "purchase"]
    df = df[df["eventName"].isin(want)].copy()
    df.rename(columns={"eventName": "단계", "eventCount": "수"}, inplace=True)
    order = {k: i for i, k in enumerate(want)}
    df["ord"] = df["단계"].map(order)
    df = df.sort_values("ord").drop(columns=["ord"])

    def rate(a, b):
        try:
            if b == 0:
                return 0.0
            return round(a / b * 100, 1)
        except Exception:
            return 0.0

    base = df.set_index("단계")["수"]
    view_cnt = base.get("view_item", 0)
    cart_cnt = base.get("add_to_cart", 0)
    chk_cnt = base.get("begin_checkout", 0)
    buy_cnt = base.get("purchase", 0)

    data = [
        {
            "구간": "상품 상세 → 장바구니",
            "기준": "PDP → Cart",
            "전환율(%)": rate(cart_cnt, view_cnt),
            "이탈율(%)": rate(view_cnt - cart_cnt, view_cnt),
            "벤치마크(전환 최소)": PDP_ADD2CART_MIN_PCT,
        },
        {
            "구간": "장바구니 → 체크아웃",
            "기준": "Cart → Checkout",
            "전환율(%)": rate(chk_cnt, cart_cnt),
            "이탈율(%)": rate(cart_cnt - chk_cnt, cart_cnt),
            "벤치마크(전환 최소)": CART2CHK_MIN_PCT,
        },
        {
            "구간": "체크아웃 → 결제완료",
            "기준": "Checkout → Purchase",
            "전환율(%)": rate(buy_cnt, chk_cnt),
            "이탈율(%)": rate(chk_cnt - buy_cnt, chk_cnt),
            "벤치마크(전환 최소)": CHK2BUY_MIN_PCT,
        },
    ]
    funnel_rate_df = pd.DataFrame(data)
    return df, funnel_rate_df


def src_traffic_yesterday():
    df = ga_run_report(
        dimensions=["sessionDefaultChannelGroup"],
        metrics=["sessions", "transactions", "newUsers"],
        start_date="yesterday",
        end_date="yesterday",
    )
    if df.empty:
        return pd.DataFrame(columns=["소스", "UV", "구매수", "CVR(%)", "신규 방문자"])
    df.rename(
        columns={
            "sessionDefaultChannelGroup": "소스",
            "sessions": "UV",
            "transactions": "구매수",
            "newUsers": "신규 방문자",
        },
        inplace=True,
    )
    df["CVR(%)"] = (df["구매수"] / df["UV"] * 100).round(2).fillna(0)
    df = df.sort_values("UV", ascending=False)
    return df


def src_search_yesterday(limit=100):
    df = ga_run_report(
        dimensions=["searchTerm"],
        metrics=["eventCount", "transactions"],
        start_date="yesterday",
        end_date="yesterday",
        limit=limit,
    )
    if df.empty:
        return pd.DataFrame(columns=["키워드", "검색수", "구매수", "CVR(%)"])
    df.rename(
        columns={
            "searchTerm": "키워드",
            "eventCount": "검색수",
            "transactions": "구매수",
        },
        inplace=True,
    )
    df["CVR(%)"] = (df["구매수"] / df["검색수"] * 100).round(2).fillna(0)
    df = df.sort_values("검색수", ascending=False)
    return df


def src_hourly_revenue_traffic():
    """어제 기준 시간대별 세션수 / 매출."""
    df = ga_run_report(
        dimensions=["hour"],
        metrics=["sessions", "purchaseRevenue"],
        start_date="yesterday",
        end_date="yesterday",
    )

    if df.empty:
        return pd.DataFrame(columns=["시간", "시간_숫자", "세션수", "매출"])

    df = df.copy()
    df["시간_숫자"] = pd.to_numeric(df["hour"], errors="coerce").fillna(0).astype(int)
    df["시간"] = df["시간_숫자"].map(lambda h: f"{h:02d}")
    df.rename(
        columns={
            "sessions": "세션수",
            "purchaseRevenue": "매출",
        },
        inplace=True,
    )
    df["세션수"] = pd.to_numeric(df["세션수"], errors="coerce").fillna(0).astype(int)
    df["매출"] = pd.to_numeric(df["매출"], errors="coerce").fillna(0.0).astype(float)
    df = df.sort_values("시간_숫자")
    return df[["시간", "시간_숫자", "세션수", "매출"]]


def src_top_products_ga(limit: int = 200) -> pd.DataFrame:
    """GA4 기준 상품별 조회/구매/매출 요약."""
    base = ga_run_report(
        dimensions=["itemName"],
        metrics=["itemsPurchased", "itemRevenue"],
        start_date="yesterday",
        end_date="yesterday",
        limit=limit,
    )
    if base.empty:
        return pd.DataFrame(columns=PRODUCT_COLS)

    base = base.rename(
        columns={
            "itemName": "상품명",
            "itemsPurchased": "구매수",
            "itemRevenue": "매출(원)",
        }
    )

    views = pd.DataFrame(columns=["상품명", "상품조회수"])
    candidates = []
    if GA_ITEM_VIEW_METRIC:
        candidates.append(GA_ITEM_VIEW_METRIC)
    for m in ["itemsViewed", "itemViews", "view_item_event_count", "eventCount"]:
        if m not in candidates:
            candidates.append(m)

    for metric_name in candidates:
        try:
            raw = ga_run_report(
                dimensions=["itemName"],
                metrics=[metric_name],
                start_date="yesterday",
                end_date="yesterday",
                limit=limit,
            )
            if raw is not None and not raw.empty and metric_name in raw.columns:
                tmp = raw[["itemName", metric_name]].copy()
                tmp = tmp.rename(
                    columns={"itemName": "상품명", metric_name: "상품조회수"}
                )
                views = tmp
                print(f"[INFO] 상품조회수 메트릭 '{metric_name}' 사용")
                break
        except Exception as e:
            print(f"[WARN] 상품조회수 메트릭 '{metric_name}' 조회 실패:", e)

    df = base.copy()
    if not views.empty:
        df = df.merge(views, on="상품명", how="left")
    else:
        df["상품조회수"] = 0

    for col in ["상품조회수", "구매수", "매출(원)"]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    df["매출(만원)"] = (df["매출(원)"] / 10_000).round(1)

    def _calc_cvr(row):
        v = row.get("상품조회수", 0)
        b = row.get("구매수", 0)
        if v <= 0:
            return 0.00
        return round((b / v) * 100, 2)

    df["CVR(%)"] = df.apply(_calc_cvr, axis=1)

    df = df.sort_values(["상품조회수", "매출(원)"], ascending=[False, False]).head(limit)

    # 조회수/구매수 정수 처리
    df["상품조회수"] = df["상품조회수"].round().astype(int)
    df["구매수"] = df["구매수"].round().astype(int)

    return df[PRODUCT_COLS]


def src_top_pages_ga(limit: int = 10) -> pd.DataFrame:
    df = ga_run_report(
        dimensions=["pagePathPlusQueryString"],
        metrics=["screenPageViews"],
        start_date="yesterday",
        end_date="yesterday",
        limit=limit,
    )
    if df.empty:
        return pd.DataFrame(columns=["페이지", "페이지뷰"])
    df = df.rename(
        columns={
            "pagePathPlusQueryString": "페이지",
            "screenPageViews": "페이지뷰",
        }
    )
    df["페이지뷰"] = pd.to_numeric(df["페이지뷰"], errors="coerce").fillna(0)
    df = df.sort_values("페이지뷰", ascending=False).head(limit)
    return df


# =====================================================================
# 5) KPI & 시그널
# =====================================================================

def _channel_uv_for_day(day_keyword: str):
    """특정 일자 기준 전체 UV / 오가닉 UV / 비오가닉 UV / 오가닉 비중."""
    df = ga_run_report(
        dimensions=["sessionDefaultChannelGroup"],
        metrics=["sessions"],
        start_date=day_keyword,
        end_date=day_keyword,
    )
    if df is None or df.empty:
        return {
            "total_uv": 0,
            "organic_uv": 0,
            "nonorganic_uv": 0,
            "organic_share": 0.0,
        }

    df = df.copy()
    df["sessions"] = pd.to_numeric(df["sessions"], errors="coerce").fillna(0).astype(int)
    total_uv = int(df["sessions"].sum())

    organic_uv = int(
        df.loc[df["sessionDefaultChannelGroup"] == "Organic Search", "sessions"].sum()
    )
    nonorganic_uv = total_uv - organic_uv
    organic_share = (organic_uv / total_uv * 100) if total_uv > 0 else 0.0

    return {
        "total_uv": total_uv,
        "organic_uv": organic_uv,
        "nonorganic_uv": nonorganic_uv,
        "organic_share": round(organic_share, 1),
    }


def build_core_kpi():
    # 기준일: 어제
    kpi_today = src_kpi_one_day("yesterday", "yesterday")
    # LD: 어제 대비 전일 (D-1 vs D-2)
    kpi_ld = src_kpi_one_day("2daysAgo", "2daysAgo")
    # LW: 전주 동일 요일
    kpi_prev = src_kpi_one_day("8daysAgo", "8daysAgo")
    # LY: 전년 동일 일자
    kpi_yoy = src_kpi_one_day("366daysAgo", "366daysAgo")

    # 기본 KPI 값
    rev_today = kpi_today["purchaseRevenue"]
    rev_ld = kpi_ld["purchaseRevenue"]
    rev_prev = kpi_prev["purchaseRevenue"]
    rev_yoy = kpi_yoy["purchaseRevenue"]

    uv_today = kpi_today["sessions"]
    uv_ld = kpi_ld["sessions"]
    uv_prev = kpi_prev["sessions"]
    uv_yoy = kpi_yoy["sessions"]

    ord_today = kpi_today["transactions"]
    ord_ld = kpi_ld["transactions"]
    ord_prev = kpi_prev["transactions"]
    ord_yoy = kpi_yoy["transactions"]

    new_today = kpi_today["newUsers"]
    new_ld = kpi_ld["newUsers"]
    new_prev = kpi_prev["newUsers"]
    new_yoy = kpi_yoy["newUsers"]

    cvr_today = (ord_today / uv_today * 100) if uv_today else 0.0
    cvr_ld = (ord_ld / uv_ld * 100) if uv_ld else 0.0
    cvr_prev = (ord_prev / uv_prev * 100) if uv_prev else 0.0
    cvr_yoy = (ord_yoy / uv_yoy * 100) if uv_yoy else 0.0

    aov_today = (rev_today / ord_today) if ord_today else 0.0
    aov_ld = (rev_ld / ord_ld) if ord_ld else 0.0
    aov_prev = (rev_prev / ord_prev) if ord_prev else 0.0
    aov_yoy = (rev_yoy / ord_yoy) if ord_yoy else 0.0

    # 오가닉 / 비오가닉 UV & 비중
    ch_today = _channel_uv_for_day("yesterday")
    ch_ld = _channel_uv_for_day("2daysAgo")
    ch_prev = _channel_uv_for_day("8daysAgo")
    ch_yoy = _channel_uv_for_day("366daysAgo")

    organic_uv_today = ch_today["organic_uv"]
    organic_uv_ld = ch_ld["organic_uv"]
    organic_uv_prev = ch_prev["organic_uv"]
    organic_uv_yoy = ch_yoy["organic_uv"]

    nonorganic_uv_today = ch_today["nonorganic_uv"]
    nonorganic_uv_ld = ch_ld["nonorganic_uv"]
    nonorganic_uv_prev = ch_prev["nonorganic_uv"]
    nonorganic_uv_yoy = ch_yoy["nonorganic_uv"]

    organic_share_today = ch_today["organic_share"]
    organic_share_ld = ch_ld["organic_share"]
    organic_share_prev = ch_prev["organic_share"]
    organic_share_yoy = ch_yoy["organic_share"]

    kpi = {
        "date_label": format_date_label(kpi_today["date"]) if kpi_today["date"] else "어제",

        # 매출
        "revenue_today": rev_today,
        "revenue_ld": rev_ld,
        "revenue_prev": rev_prev,
        "revenue_yoy": rev_yoy,
        "revenue_ld_pct": pct_change(rev_today, rev_ld),
        "revenue_lw_pct": pct_change(rev_today, rev_prev),
        "revenue_ly_pct": pct_change(rev_today, rev_yoy),

        # UV
        "uv_today": uv_today,
        "uv_ld": uv_ld,
        "uv_prev": uv_prev,
        "uv_yoy": uv_yoy,
        "uv_ld_pct": pct_change(uv_today, uv_ld),
        "uv_lw_pct": pct_change(uv_today, uv_prev),
        "uv_ly_pct": pct_change(uv_today, uv_yoy),

        # 주문수
        "orders_today": ord_today,
        "orders_ld": ord_ld,
        "orders_prev": ord_prev,
        "orders_yoy": ord_yoy,
        "orders_ld_pct": pct_change(ord_today, ord_ld),
        "orders_lw_pct": pct_change(ord_today, ord_prev),
        "orders_ly_pct": pct_change(ord_today, ord_yoy),

        # CVR
        "cvr_today": round(cvr_today, 2),
        "cvr_ld": round(cvr_ld, 2),
        "cvr_prev": round(cvr_prev, 2),
        "cvr_yoy": round(cvr_yoy, 2),
        "cvr_ld_pct": pct_change(cvr_today, cvr_ld),
        "cvr_lw_pct": pct_change(cvr_today, cvr_prev),
        "cvr_ly_pct": pct_change(cvr_today, cvr_yoy),

        # AOV
        "aov_today": aov_today,
        "aov_ld": aov_ld,
        "aov_prev": aov_prev,
        "aov_yoy": aov_yoy,
        "aov_ld_pct": pct_change(aov_today, aov_ld),
        "aov_lw_pct": pct_change(aov_today, aov_prev),
        "aov_ly_pct": pct_change(aov_today, aov_yoy),

        # 신규 방문자
        "new_today": new_today,
        "new_ld": new_ld,
        "new_prev": new_prev,
        "new_yoy": new_yoy,
        "new_ld_pct": pct_change(new_today, new_ld),
        "new_lw_pct": pct_change(new_today, new_prev),
        "new_ly_pct": pct_change(new_today, new_yoy),

        # 오가닉 UV
        "organic_uv_today": organic_uv_today,
        "organic_uv_ld": organic_uv_ld,
        "organic_uv_prev": organic_uv_prev,
        "organic_uv_yoy": organic_uv_yoy,
        "organic_uv_ld_pct": pct_change(organic_uv_today, organic_uv_ld),
        "organic_uv_lw_pct": pct_change(organic_uv_today, organic_uv_prev),
        "organic_uv_ly_pct": pct_change(organic_uv_today, organic_uv_yoy),

        # 비오가닉 UV
        "nonorganic_uv_today": nonorganic_uv_today,
        "nonorganic_uv_ld": nonorganic_uv_ld,
        "nonorganic_uv_prev": nonorganic_uv_prev,
        "nonorganic_uv_yoy": nonorganic_uv_yoy,
        "nonorganic_uv_ld_pct": pct_change(nonorganic_uv_today, nonorganic_uv_ld),
        "nonorganic_uv_lw_pct": pct_change(nonorganic_uv_today, nonorganic_uv_prev),
        "nonorganic_uv_ly_pct": pct_change(nonorganic_uv_today, nonorganic_uv_yoy),

        # 오가닉 UV 비중
        "organic_share_today": organic_share_today,
        "organic_share_ld": organic_share_ld,
        "organic_share_prev": organic_share_prev,
        "organic_share_yoy": organic_share_yoy,
        "organic_share_ld_pct": pct_change(organic_share_today, organic_share_ld),
        "organic_share_lw_pct": pct_change(organic_share_today, organic_share_prev),
        "organic_share_ly_pct": pct_change(organic_share_today, organic_share_yoy),
    }
    return kpi


def build_signals(kpi, funnel_rate_df, traffic_df, search_df):
    """GA4 데이터 기반 핵심 인사이트 문장 리스트 (최대 4개)."""
    signals = []

    # 1) 매출 / UV / CVR
    if kpi["revenue_lw_pct"] > 0 and kpi["cvr_lw_pct"] > 0:
        signals.append(
            f"· 매출이 전주 동일 요일 대비 {kpi['revenue_lw_pct']:.1f}% ↑, CVR은 {kpi['cvr_lw_pct']:.1f}p 개선되었습니다."
        )
    elif kpi["revenue_lw_pct"] < 0 and kpi["uv_lw_pct"] < 0:
        signals.append(
            f"· 매출({kpi['revenue_lw_pct']:.1f}%)과 UV({kpi['uv_lw_pct']:.1f}%)가 함께 감소해 상단 퍼널 유입 점검이 필요합니다."
        )
    else:
        signals.append(
            f"· 매출 {kpi['revenue_lw_pct']:.1f}%, UV {kpi['uv_lw_pct']:.1f}%, CVR {kpi['cvr_lw_pct']:.1f}p 변동을 보였습니다."
        )

    # 2) 퍼널 이탈
    if funnel_rate_df is not None and not funnel_rate_df.empty:
        high_drop = funnel_rate_df[
            funnel_rate_df["전환율(%)"] < funnel_rate_df["벤치마크(전환 최소)"]
        ]
        if not high_drop.empty:
            names = ", ".join(high_drop["구간"].tolist())
            signals.append(
                f"· 퍼널 기준 이탈이 큰 구간은 {names}로, 해당 단계 UI/혜택/카피 점검이 우선입니다."
            )
        else:
            signals.append("· 퍼널 전환율은 설정한 벤치마크 이상으로 전반적으로 안정적입니다.")

    # 3) 채널
    if traffic_df is not None and not traffic_df.empty:
        top = traffic_df.iloc[0]
        signals.append(
            f"· 유입은 {top['소스']} 채널(UV {int(top['UV']):,}명, CVR {top['CVR(%)']:.2f}%) 비중이 가장 큽니다."
        )

    # 4) 검색
    if search_df is not None and not search_df.empty:
        bad = search_df[search_df["CVR(%)"] < SEARCH_CVR_MIN]
        if not bad.empty:
            top_bad = bad.head(2)["키워드"].tolist()
            signals.append(
                f"· 저전환 검색어(CVR {SEARCH_CVR_MIN}% 미만)는 {', '.join(top_bad)} 등이 있어 결과 보완이 필요합니다."
            )

    fallback = [
        "· 오늘은 전반적인 트렌드를 중심으로 지표를 확인해 주세요.",
        "· 주요 채널·퍼널 구간·상품 성과를 함께 보면서 액션 포인트를 잡을 수 있습니다.",
    ]
    while len(signals) < 4:
        signals.append(fallback[len(signals) % len(fallback)])

    return signals[:4]


def build_actions(kpi, funnel_rate_df, traffic_df, search_df):
    """오늘 취할 액션 리스트 (최대 4개)."""
    actions = []

    # 1) 상단 퍼널 / CVR 액션
    if kpi["revenue_lw_pct"] < 0 and kpi["uv_lw_pct"] < 0:
        actions.append("· 매출·UV가 동반 하락 중이므로 상단 퍼널 신규 유입 캠페인(소재·입찰·예산)을 우선 점검합니다.")
    elif kpi["cvr_lw_pct"] < 0:
        actions.append("· CVR이 전주 대비 하락해 모바일 장바구니·체크아웃 구간의 전환율과 UX를 집중적으로 확인합니다.")
    else:
        actions.append("· 성과가 좋은 채널/소재의 예산을 소폭 상향해 상승 구간을 더 밀어주는 실험을 진행합니다.")

    # 2) 퍼널 이탈 액션
    if funnel_rate_df is not None and not funnel_rate_df.empty:
        high_drop = funnel_rate_df[
            funnel_rate_df["전환율(%)"] < funnel_rate_df["벤치마크(전환 최소)"]
        ]
        if not high_drop.empty:
            actions.append("· 이탈이 큰 퍼널 구간의 배송비·쿠폰·CTA 카피를 이번 주 안에 최소 1개 이상 테스트합니다.")
        else:
            actions.append("· 퍼널이 안정적인 편이므로 신규 유입 확대 및 VIP 재구매 쪽으로 테스트 리소스를 배분합니다.")
    else:
        actions.append("· 퍼널 데이터가 부족해 우선 전체 전환율 흐름을 모니터링하면서, 채널/상품 단위의 이상만 체크합니다.")

    # 3) 채널 액션
    if traffic_df is not None and not traffic_df.empty:
        top = traffic_df.iloc[0]
        actions.append(
            f"· {top['소스']} 채널의 성과 좋은 소재를 기준으로 유사 카피·이미지를 다른 채널에도 확장 테스트합니다."
        )

    # 4) 검색 액션
    if search_df is not None and not search_df.empty:
        bad = search_df[search_df["CVR(%)"] < SEARCH_CVR_MIN]
        if not bad.empty:
            actions.append("· 저전환 검색어의 노출 상품/필터를 재구성하거나, 상세 설명·가격 정책을 조정하는 안을 검토합니다.")
        else:
            actions.append("· 상위 검색어 기준으로 기획전/컬렉션 페이지를 추가 구성해 전환을 더 끌어올릴 수 있는지 테스트합니다.")

    fallback = [
        "· 오늘 눈에 띄는 채널/상품 1~2개를 선정해 소규모 예산으로 실험을 바로 실행합니다.",
    ]
    while len(actions) < 4:
        actions.append(fallback[0])

    return actions[:4]


# =====================================================================
# 6) HTML 템플릿
# =====================================================================

def compose_html_daily(
    kpi,
    funnel_counts_df,
    funnel_rate_df,
    traffic_df,
    hourly_df,
    search_df,
    products_top_df,
    products_lowconv_df,
    products_hiconv_df,
    pages_df,
):
    # ---- 섹션2용: 작은 카드 ----
    def df_to_html_box(title, subtitle, df, max_rows=None):
        if df is None or df.empty:
            table_html = "<p style='color:#999;font-size:11px;margin:4px 0 0 0;'>데이터 없음</p>"
        else:
            if max_rows is not None:
                df = df.head(max_rows)
            inner = df.to_html(index=False, border=0, justify="left", escape=False)
            inner = inner.replace(
                '<table border="0" class="dataframe">',
                '<table style="width:100%; border-collapse:collapse; font-size:10px;">',
            )
            inner = inner.replace(
                '<tr style="text-align: right;">',
                '<tr style="background:#f4f6fb; text-align:left;">',
            )
            inner = inner.replace(
                "<th>",
                "<th style=\\"padding:3px 6px; border-bottom:1px solid #e1e4f0; "
                "text-align:left; font-weight:600; color:#555;\\">",
            )
            inner = inner.replace(
                "<td>",
                "<td style=\\"padding:3px 6px; border-bottom:1px solid #f1f3fa; "
                "text-align:left; color:#333;\\">",
            )
            table_html = inner

        return f\"\"\"
<table width="100%" cellpadding="0" cellspacing="0"
       style="background:#ffffff; border-radius:12px;
              border:1px solid #e1e7f5; box-shadow:0 3px 10px rgba(0,0,0,0.03);
              padding:8px 10px; border-collapse:separate; min-height:180px;">
  <tr><td>
    <div style="font-size:11px; font-weight:600; color:#224; margin-bottom:2px;">
      {title}
    </div>
    <div style="font-size:10px; color:#888; margin-bottom:6px; line-height:1.4;">
      {subtitle}
    </div>
    {table_html}
  </td></tr>
</table>
\"\"\"

    # ---- 시간대별 카드: 트래픽 막대 + 매출 막대 ----
    def build_hourly_card(df):
        if df is None or df.empty:
            body_html = "<p style='color:#999;font-size:11px;margin:4px 0 0 0;'>데이터 없음</p>"
            return f\"\"\"
<table width="100%" cellpadding="0" cellspacing="0"
       style="background:#ffffff; border-radius:12px;
              border:1px solid #e1e7f5; box-shadow:0 3px 10px rgba(0,0,0,0.03);
              padding:10px 12px; border-collapse:separate; margin-top:10px;">
  <tr><td>
    <div style="font-size:11px; font-weight:600; color:#224; margin-bottom:2px;">
      시간대별 트래픽 & 매출 (막대)
    </div>
    <div style="font-size:10px; color:#888; margin-bottom:6px; line-height:1.4;">
      어제 0~23시 기준 — 위에는 트래픽(세션), 아래에는 매출을 시간대별 막대그래프로 비교해서 볼 수 있습니다.
    </div>
    {body_html}
  </td></tr>
</table>
\"\"\"

        df = df.copy()

        # 숫자/타입 정리
        if "시간_숫자" not in df.columns:
            df["시간_숫자"] = (
                df["시간"]
                .astype(str)
                .str.extract(r"(\\d+)")
                .fillna("0")
                .astype(int)
            )

        df["세션수"] = pd.to_numeric(df["세션수"], errors="coerce").fillna(0)
        df["매출"]   = pd.to_numeric(df["매출"], errors="coerce").fillna(0.0)

        df = df.sort_values("시간_숫자")

        hours    = df["시간_숫자"].tolist()
        sessions = df["세션수"].tolist()
        revenue  = df["매출"].tolist()

        if not hours:
            return ""

        max_sess = max(sessions) if max(sessions) > 0 else 1
        max_rev  = max(revenue)  if max(revenue)  > 0 else 1

        # 막대 최대 높이(px)
        max_bar_height = 80

        # 공통 x축 라벨
        labels_row = "".join(
            f"<td style='font-size:9px; color:#666; padding-top:2px; text-align:center;'>{int(h):02d}</td>"
            for h in hours
        )

        # 트래픽 막대들
        sess_bar_row = ""
        for s in sessions:
            ratio = s / max_sess if max_sess > 0 else 0
            h = max(3, int(ratio * max_bar_height))
            sess_bar_row += f\"\"\"
<td style="vertical-align:bottom; text-align:center;">
  <div style="margin:0 auto; width:10px; height:{h}px;
              border-radius:999px 999px 0 0; background:#2563eb;"></div>
</td>
\"\"\"

        traffic_chart_html = f\"\"\"
<div style="font-size:10px; color:#555; margin-bottom:4px;">
  · 트래픽 (세션수, 막대)
</div>
<table cellpadding="0" cellspacing="0" style="width:100%; border-collapse:collapse;">
  <tr style="height:{max_bar_height+15}px; vertical-align:bottom;">
    {sess_bar_row}
  </tr>
  <tr>
    {labels_row}
  </tr>
</table>
\"\"\"

        # 매출 막대들
        rev_bar_row = ""
        for r in revenue:
            ratio = r / max_rev if max_rev > 0 else 0
            h = max(3, int(ratio * max_bar_height))
            rev_bar_row += f\"\"\"
<td style="vertical-align:bottom; text-align:center;">
  <div style="margin:0 auto; width:10px; height:{h}px;
              border-radius:999px 999px 0 0; background:#fb923c;"></div>
</td>
\"\"\"

        revenue_chart_html = f\"\"\"
<div style="font-size:10px; color:#555; margin-top:12px; margin-bottom:4px;">
  · 매출 (원, 막대)
</div>
<table cellpadding="0" cellspacing="0" style="width:100%; border-collapse:collapse;">
  <tr style="height:{max_bar_height+15}px; vertical-align:bottom;">
    {rev_bar_row}
  </tr>
  <tr>
    {labels_row}
  </tr>
</table>
\"\"\"

        body_html = traffic_chart_html + revenue_chart_html

        return f\"\"\"
<table width="100%" cellpadding="0" cellspacing="0"
       style="background:#ffffff; border-radius:12px;
              border:1px solid #e1e7f5; box-shadow:0 3px 10px rgba(0,0,0,0.03);
              padding:10px 12px; border-collapse:separate; margin-top:10px;">
  <tr><td>
    <div style="font-size:11px; font-weight:600; color:#224; margin-bottom:2px;">
      시간대별 트래픽 & 매출 (막대)
    </div>
    <div style="font-size:10px; color:#888; margin-bottom:6px; line-height:1.4;">
      어제 0~23시 기준 — 위에는 트래픽(세션), 아래에는 매출을 시간대별 막대그래프로 비교해서 볼 수 있습니다.
    </div>
    {body_html}
  </td></tr>
</table>
\"\"\"

    # ---- 인사이트 & 액션 카드 내용 ----
    signals_list = build_signals(kpi, funnel_rate_df, traffic_df, search_df)
    actions_list = build_actions(kpi, funnel_rate_df, traffic_df, search_df)

    insight_items_html = "".join(
        f"<li style='margin-bottom:3px;'>{s}</li>" for s in signals_list
    )
    action_items_html = "".join(
        f"<li style='margin-bottom:3px;'>{s}</li>" for s in actions_list
    )

    insight_card_html = f\"\"\"
<table width="100%" cellpadding="0" cellspacing="0"
       style="background:#ffffff; border-radius:14px;
              border:1px solid #e1e7f5; box-shadow:0 4px 12px rgba(0,0,0,0.04);
              padding:10px 12px; border-collapse:separate;">
  <tr><td>
    <div style="font-size:11px; font-weight:600; color:#004a99; margin-bottom:4px;">
      오늘의 인사이트
    </div>
    <ul style="margin:0; padding-left:16px; font-size:11px; color:#555; line-height:1.6;">
      {insight_items_html}
    </ul>
  </td></tr>
</table>
\"\"\"

    action_card_html = f\"\"\"
<table width="100%" cellpadding="0" cellspacing="0"
       style="background:#ffffff; border-radius:14px;
              border:1px solid #e1e7f5; box-shadow:0 4px 12px rgba(0,0,0,0.04);
              padding:10px 12px; border-collapse:separate;">
  <tr><td>
    <div style="font-size:11px; font-weight:600; color:#0f766e; margin-bottom:4px;">
      오늘 취할 액션
    </div>
    <ul style="margin:0; padding-left:16px; font-size:11px; color:#555; line-height:1.6;">
      {action_items_html}
    </ul>
  </td></tr>
</table>
\"\"\"

    insight_action_html = f\"\"\"
<!-- Insight & Action Cards -->
<table width="100%" cellpadding="0" cellspacing="0"
       style="border-collapse:separate; border-spacing:8px 10px; margin-top:14px;">
  <tr>
    <td width="50%" valign="top">{insight_card_html}</td>
    <td width="50%" valign="top">{action_card_html}</td>
  </tr>
</table>
\"\"\"

    # ---- 섹션2 카드 정의 ----
    funnel_counts_box = df_to_html_box(
        "퍼널 전환 (view → cart → checkout → purchase)",
        "단계별 이벤트 수 기준 전환 흐름입니다.",
        funnel_counts_df,
        max_rows=None,
    )
    funnel_rate_box = df_to_html_box(
        "퍼널 이탈/전환율 & 벤치마크 비교",
        "이탈율이 벤치마크보다 높으면 위험 구간으로 볼 수 있습니다.",
        funnel_rate_df.assign(
            위험=lambda d: d.apply(
                lambda r: "위험" if r["전환율(%)"] < r["벤치마크(전환 최소)"] else "",
                axis=1,
            )
        ),
        max_rows=None,
    )
    traffic_box = df_to_html_box(
        "채널별 유입 & 오가닉",
        "채널별 UV · 구매수 · 신규 방문자 · CVR입니다.",
        traffic_df,
        max_rows=None,
    )
    pages_box = df_to_html_box(
        "많이 본 페이지 TOP 10",
        "페이지뷰 기준 상위 페이지입니다.",
        pages_df,
        max_rows=10,
    )
    products_top_box = df_to_html_box(
        "지금 치고 올라오는 상품",
        "조회수·매출 기준 상위 상품입니다.",
        products_top_df[PRODUCT_COLS],
        max_rows=7,
    )
    products_low_box = df_to_html_box(
        "조회는 많은데 구매 전환이 낮은 상품",
        "조회 TOP 30 중 CVR 하위 상품입니다.",
        products_lowconv_df[PRODUCT_COLS] if not products_lowconv_df.empty else products_lowconv_df,
        max_rows=5,
    )
    products_hi_box = df_to_html_box(
        "조회는 적지만 구매 전환이 좋은 상품",
        "조회 하위 구간 중 CVR 상위 상품입니다.",
        products_hiconv_df[PRODUCT_COLS] if not products_hiconv_df.empty else products_hiconv_df,
        max_rows=5,
    )
    search_top_box = df_to_html_box(
        "온사이트 검색 상위 키워드",
        "검색수 기준 상위 키워드와 CVR입니다.",
        search_df[["키워드", "검색수", "구매수", "CVR(%)"]] if not search_df.empty else search_df,
        max_rows=10,
    )

    hourly_box = build_hourly_card(hourly_df)

    section2_grid_html = f\"\"\"
<div style="font-size:11px; letter-spacing:0.12em; color:#6d7a99; margin-top:20px; margin-bottom:8px;">
  02 · FUNNEL · TRAFFIC · PRODUCT · SEARCH
</div>
<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:4px;">
  <tr>
    <td width="50%" valign="top" style="padding:4px 6px 8px 0;">{funnel_counts_box}</td>
    <td width="50%" valign="top" style="padding:4px 0 8px 6px;">{funnel_rate_box}</td>
  </tr>
  <tr>
    <td width="50%" valign="top" style="padding:4px 6px 8px 0;">{traffic_box}</td>
    <td width="50%" valign="top" style="padding:4px 0 8px 6px;">{pages_box}</td>
  </tr>
  <tr>
    <td width="50%" valign="top" style="padding:4px 6px 8px 0;">{products_top_box}</td>
    <td width="50%" valign="top" style="padding:4px 0 8px 6px;">{products_low_box}</td>
  </tr>
  <tr>
    <td width="50%" valign="top" style="padding:4px 6px 0 0;">{products_hi_box}</td>
    <td width="50%" valign="top" style="padding:4px 0 0 6px;">{search_top_box}</td>
  </tr>
</table>
<div>
  {hourly_box}
</div>
\"\"\"

    # ---- 본문 HTML ----
    html = f\"\"\"<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<title>Columbia Sportswear Korea — Daily eCommerce Performance Digest</title>
</head>
<body style="margin:0; padding:0; background:#f5f7fb; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans KR',Arial,sans-serif;">

<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f7fb;">
  <tr>
    <td align="center">
      <table role="presentation" width="900" cellspacing="0" cellpadding="0" style="padding:24px 12px 24px 12px; background:#f5f7fb;">
        <tr>
          <td>

            <!-- 헤더 -->
            <table role="presentation" width="100%" cellspacing="0" cellpadding="0"
                   style="background:#ffffff; border-radius:18px; border:1px solid #e6e9ef; box-shadow:0 6px 18px rgba(0,0,0,0.06);">
              <tr>
                <td valign="top" style="padding:18px 20px 16px 20px;">
                  <div style="font-size:18px; font-weight:700; color:#0055a5; margin-bottom:2px;">
                    COLUMBIA SPORTSWEAR KOREA
                  </div>
                  <div style="font-size:13px; color:#555; margin-bottom:8px;">
                    Daily eCommerce Performance Digest
                  </div>
                  <span style="display:inline-block; font-size:11px; padding:4px 10px; border-radius:999px;
                               background:#eaf3ff; color:#0055a5; margin-bottom:6px;">
                    {kpi['date_label']} 기준 (어제 데이터)
                  </span>
                  <div style="font-size:11px; color:#777; margin-top:6px; margin-bottom:2px; line-height:1.6;">
                    매출·UV·CVR 흐름과 퍼널 · 온사이트 검색 · 상품 성과를 한 번에 보는 데일리 요약입니다.
                  </div>
                </td>

                <td valign="top" align="right" style="padding:16px 20px 16px 0%;">
                  <table role="presentation" cellspacing="0" cellpadding="0" align="right" style="margin-bottom:8px;">
                    <tr>
                      <td style="padding:0 3px;">
                        <span style="display:inline-block; font-size:10px; padding:4px 9px; border-radius:999px;
                                     background:#0055a5; color:#ffffff; border:1px solid #0055a5;">
                          DAILY
                        </span>
                      </td>
                      <td style="padding:0 3px;">
                        <span style="display:inline-block; font-size:10px; padding:4px 9px; border-radius:999px;
                                     background:#fafbfd; color:#445; border:1px solid #dfe6f3;">
                          KPI
                        </span>
                      </td>
                      <td style="padding:0 3px;">
                        <span style="display:inline-block; font-size:10px; padding:4px 9px; border-radius:999px;
                                     background:#fafbfd; color:#445; border:1px solid #dfe6f3;">
                          FUNNEL
                        </span>
                      </td>
                      <td style="padding:0 3px;">
                        <span style="display:inline-block; font-size:10px; padding:4px 9px; border-radius:999px;
                                     background:#fafbfd; color:#445; border:1px solid #dfe6f3;">
                          SEARCH
                        </span>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>

{insight_action_html}

<!-- 01 KPI -->
<div style="font-size:11px; letter-spacing:0.12em; color:#6d7a99; margin-top:18px; margin-bottom:10px;">
  01 · EXECUTIVE KPI SNAPSHOT
</div>

<!-- KPI 9개 카드 (3 x 3) -->
<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:separate; border-spacing:8px 10px;">
  <tr>
    <!-- 매출 -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">매출 (Revenue)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {format_money_manwon(kpi['revenue_today'])}
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {format_money_manwon(kpi['revenue_ld'])} · LW: {format_money_manwon(kpi['revenue_prev'])} · LY: {format_money_manwon(kpi['revenue_yoy'])}
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['revenue_ld_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['revenue_lw_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['revenue_ly_pct']:+.1f}%
          </span>
        </div>
      </div>
    </td>

    <!-- 방문자수 -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">방문자수 (UV)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {kpi['uv_today']:,}명
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {kpi['uv_ld']:,}명 · LW: {kpi['uv_prev']:,}명 · LY: {kpi['uv_yoy']:,}명
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['uv_ld_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['uv_lw_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['uv_ly_pct']:+.1f}%
          </span>
        </div>
      </div>
    </td>

    <!-- 전환율 -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">전환율 (CVR)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {kpi['cvr_today']:.2f}%
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {kpi['cvr_ld']:.2f}% · LW: {kpi['cvr_prev']:.2f}% · LY: {kpi['cvr_yoy']:.2f}%
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['cvr_ld_pct']:+.1f}p
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['cvr_lw_pct']:+.1f}p
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['cvr_ly_pct']:+.1f}p
          </span>
        </div>
      </div>
    </td>
  </tr>
  <tr>
    <!-- 구매수 -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">구매수 (Orders)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {kpi['orders_today']:,}건
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {kpi['orders_ld']:,}건 · LW: {kpi['orders_prev']:,}건 · LY: {kpi['orders_yoy']:,}건
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['orders_ld_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['orders_lw_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['orders_ly_pct']:+.1f}%
          </span>
        </div>
      </div>
    </td>

    <!-- 객단가 -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">객단가 (AOV)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {format_money(kpi['aov_today'])}
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {format_money(kpi['aov_ld'])} · LW: {format_money(kpi['aov_prev'])} · LY: {format_money(kpi['aov_yoy'])}
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['aov_ld_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['aov_lw_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['aov_ly_pct']:+.1f}%
          </span>
        </div>
      </div>
    </td>

    <!-- 신규 방문자 -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">신규 방문자 (New Visitors)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {kpi['new_today']:,}명
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {kpi['new_ld']:,}명 · LW: {kpi['new_prev']:,}명 · LY: {kpi['new_yoy']:,}명
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['new_ld_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['new_lw_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['new_ly_pct']:+.1f}%
          </span>
        </div>
      </div>
    </td>
  </tr>
  <tr>
    <!-- 오가닉 UV -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">오가닉 UV (Organic Search)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {kpi['organic_uv_today']:,}명
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {kpi['organic_uv_ld']:,}명 · LW: {kpi['organic_uv_prev']:,}명 · LY: {kpi['organic_uv_yoy']:,}명
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['organic_uv_ld_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['organic_uv_lw_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['organic_uv_ly_pct']:+.1f}%
          </span>
        </div>
      </div>
    </td>

    <!-- 비오가닉 UV -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">비오가닉 UV (Non-organic)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {kpi['nonorganic_uv_today']:,}명
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {kpi['nonorganic_uv_ld']:,}명 · LW: {kpi['nonorganic_uv_prev']:,}명 · LY: {kpi['nonorganic_uv_yoy']:,}명
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['nonorganic_uv_ld_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['nonorganic_uv_lw_pct']:+.1f}%
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['nonorganic_uv_ly_pct']:+.1f}%
          </span>
        </div>
      </div>
    </td>

    <!-- 오가닉 UV 비중 -->
    <td width="33.3%" valign="top">
      <div style="background:#ffffff; border-radius:16px; padding:14px 16px; border:1px solid #e1e7f5;">
        <div style="font-size:11px; color:#777; margin-bottom:4px;">오가닉 UV 비중 (Share)</div>
        <div style="font-size:18px; font-weight:700; margin-bottom:4px;">
          {kpi['organic_share_today']:.1f}%
        </div>
        <div style="font-size:10px; color:#999; margin-bottom:4px;">
          LD: {kpi['organic_share_ld']:.1f}% · LW: {kpi['organic_share_prev']:.1f}% · LY: {kpi['organic_share_yoy']:.1f}%
        </div>
        <div>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#e7f5ec; color:#1b7f4d; margin-right:4px;">
            LD {kpi['organic_share_ld_pct']:+.1f}p
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#dbeafe; color:#1d4ed8; margin-right:4px;">
            LW {kpi['organic_share_lw_pct']:+.1f}p
          </span>
          <span style="display:inline-block; font-size:10px; padding:2px 7px; border-radius:999px; background:#fdeaea; color:#c53030;">
            LY {kpi['organic_share_ly_pct']:+.1f}p
          </span>
        </div>
      </div>
    </td>
  </tr>
</table>

{section2_grid_html}

<div style="margin-top:18px; font-size:10px; color:#99a; text-align:right;">
  Columbia Sportswear Korea · Daily eCommerce Digest · GA4 · Python
</div>

          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

</body>
</html>
\"\"\"
    return html


# =====================================================================
# 7) 메인: 데일리 다이제스트 생성 & 발송
# =====================================================================

def send_daily_digest():
    # GA4 데이터
    kpi = build_core_kpi()
    funnel_counts_df, funnel_rate_df = src_funnel_yesterday()
    traffic_df = src_traffic_yesterday()
    search_df = src_search_yesterday(limit=100)
    hourly_df = src_hourly_revenue_traffic()

    products_all = src_top_products_ga(limit=200)
    pages_df = src_top_pages_ga(limit=10)

    # 상품 파생
    products_top_df = products_all.sort_values("상품조회수", ascending=False)

    products_lowconv_df = pd.DataFrame(columns=PRODUCT_COLS)
    products_hiconv_df = pd.DataFrame(columns=PRODUCT_COLS)

    if not products_all.empty:
        tmp_top = products_all.sort_values("상품조회수", ascending=False).head(30)
        products_lowconv_df = tmp_top.sort_values("CVR(%)", ascending=True).head(10)

        tmp_low = products_all.sort_values("상품조회수", ascending=True).head(50)
        products_hiconv_df = tmp_low.sort_values("CVR(%)", ascending=False).head(10)

    html = compose_html_daily(
        kpi=kpi,
        funnel_counts_df=funnel_counts_df,
        funnel_rate_df=funnel_rate_df,
        traffic_df=traffic_df,
        hourly_df=hourly_df,
        search_df=search_df,
        products_top_df=products_top_df,
        products_lowconv_df=products_lowconv_df,
        products_hiconv_df=products_hiconv_df,
        pages_df=pages_df,
    )

    # 간단 이상 감지
    critical_reasons = []
    if kpi["cvr_lw_pct"] <= -CVR_DROP_PPTS:
        critical_reasons.append(f"CVR LW 대비 {CVR_DROP_PPTS}p 이상 하락")
    if kpi["revenue_lw_pct"] <= -REVENUE_DROP_PCT:
        critical_reasons.append(f"매출 LW 대비 {REVENUE_DROP_PCT}% 이상 하락")
    if kpi["uv_lw_pct"] <= -UV_DROP_PCT:
        critical_reasons.append(f"UV LW 대비 {UV_DROP_PCT}% 이상 하락")

    if critical_reasons:
        body = " / ".join(critical_reasons)
        body += (
            f"\\n\\n어제 기준 CVR {kpi['cvr_today']:.2f}%, "
            f"매출 {format_money_manwon(kpi['revenue_today'])}, "
            f"UV {kpi['uv_today']:,}명."
        )
        send_critical_alert("⚠️ [Critical] Columbia Daily 지표 이상 감지", body)

    subject = "[Daily] Columbia eCommerce Performance Digest"

    jpeg_path = html_to_jpeg(html)
    send_email_html(subject, html, DAILY_RECIPIENTS, jpeg_path=jpeg_path)


if __name__ == "__main__":
    send_daily_digest()



import nest_asyncio, asyncio
from pyppeteer import launch

nest_asyncio.apply()

async def capture_digest():
    browser = await launch(headless=True, args=["--no-sandbox"])
    page = await browser.newPage()
    await page.setViewport({"width": 1200, "height": 1600})  # 폭은 네 레이아웃 기준으로 맞춘 거
    await page.goto("file:///content/columbia_digest_preview.html", waitUntil="networkidle0")
    await page.screenshot(path="/content/columbia_digest_preview.jpg",
                          fullPage=True,
                          type="jpeg",
                          quality=95)
    await browser.close()

if __name__ == "__main__":
    import asyncio
    asyncio.run(capture_digest())
''')

path = "/mnt/data/columbia_daily_digest_ld_organic.py"
with open(path, "w", encoding="utf-8") as f:
    f.write(code)

path
